### ISSUE TITLE
Jade - L-BTC balance not shown within SideSwap

### ISSUE THREAD

**Issue by zyklopisch** [sideswap-io/sideswapclient#24]
After logging in with Jade Hardware Wallet, the L-BTC balance is not shown, it only shows 0. On Jade itself there is a balance on the Multisig-L-BTC-wallet (not on the Singlesig). Is there some trick to make the Multisig-balance visible?

**Comment by sideswap-io** [comment]
Thank you for reaching out. 

If we understand the issue correctly:
1. You have a balance on your multisig (AMP) wallet from Green?
2. Jade was imported via SideSwap and no balance is shown on screen in your AMP wallet?

Please ensure that your multi-signature wallet is an AMP enabled wallet with an AMP ID in Green.

FYI. The wallet can sometimes takes two-three minutes to sync. Once this is done, the balances will be cached and loaded in background on next launch to check if there are updates.

If this doesn't help, please provide further details.

**Comment by zyklopisch** [comment]
Sorry, did not understand first that it needs to be an AMP-wallet (it is a normal multisig).
