### ISSUE TITLE
Total Value in wallet oscillates

### ISSUE THREAD

**Issue by starius** [sideswap-io/sideswapclient#29]
L-BTC is the only asset in the wallet. There are 3302 satoshis of L-BTC. The total value of the wallet oscillates in the range 3300 to 3304 sats every few seconds. I guess it can be related to price movements, but they should not affect the total value measured in sats.

![image](https://github.com/sideswap-io/sideswapclient/assets/920155/1593d111-f202-4718-bdce-e099c15db305)

**Comment by sideswap-io** [comment]
Thank you for reporting. Issue has been resolved and new builds are available.

While the individual asset rows are correct, we calculated the total LBTC value of the portfolio from the USD amount. Rounding errors gave rise to slippage. We now sum the LBTC amounts and produce a USD amount.

**Comment by starius** [comment]
Thank you! It makes sense.

I suggest that for accounts having only USDt it makes sense to use the old procedure to avoid a similar problem in-reverse.

The latest release lacks signatures. Can you sign it, please?

**Comment by sideswap-io** [comment]
Fixed in latest release (1.6.0).

**Comment by sideswap-io** [comment]
Fixed in latest release (1.6.0).
