### ISSUE TITLE
Bug: Error when trying to send "MAX" with coin control

### ISSUE THREAD

**Issue by vindard** [sideswap-io/sideswapclient#42]
## Description

**Desktop version: `v1.5.4`**

I have 3 outputs in my regular wallet. If I select 1 output or 2 outputs and am trying to send "max" with them to a Green wallet 2-of-2 address I get the following error. Asset is L-BTC.

If I don't select "max" and I send an amount below enough to cover fees it works fine.

![image](https://github.com/sideswap-io/sideswapclient/assets/17693119/f7c4bc32-eb15-4478-bddf-4c80b585b8a0)

https://github.com/sideswap-io/sideswapclient/blob/3e70137d3b1991885687299138c62828fc8dce5a/rust/sideswap_client/src/gdk_ses_impl.rs#L1157

**Comment by sideswap-io** [comment]
Fixed in latest release (1.6.0).

**Comment by sideswap-io** [comment]
Fixed in latest release (1.6.0).
