### ISSUE TITLE
Bug: Escaping while broadcasting tx prevents sending anymore

### ISSUE THREAD

**Issue by tohrxyz** [sideswap-io/sideswapclient#45]
### Describe issue
Hey, today I've been transacting on liquid testnet network and escaped from tx screen during broadcast, which prevented me from sending other transactions, until I restarted the app.

### Steps to reproduce

1. create transaction
2. send it
3. enter pin code to confirm
4. *starts broadcasting*
5. escape the screen (esc key)
6. try to send other transaction -> "review" button disabled
7. restart app -> works

Btw. the transaction that had it's broadcast interrupted haven't been sent at all.

### Platform and Version
MacOS 14.5
SideSwap 1.4.9

**Comment by sideswap-io** [comment]
Thanks. We're not able to reproduce issue.
