### ISSUE TITLE
[Feature Request]: Add native Tether USDt transactions

### ISSUE THREAD

**Issue by Sami32** [sideswap-io/sideswapclient#51]
Add support for native Tether USDt transactions, meaning you can pay Liquid Network fees with USDt. L-BTC is no longer required.

**Comment by sideswap-io** [comment]
This has already been implemented in SideSwap (desktop). Please try it out.

**Comment by Sami32** [comment]
Sorry, i only use your mobile App.
I should have specified that my request apply to your mobile App that still doesn't support it.
